# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba056d54ab5bc54143dc055ac38a9b143842393f57278fb671f3b73f774d53defb63af152b814b137fb60b90b81c66369c281f8ed0e60da6a4c3bf995f49a53f

test:
  secret_key_base: 4666967d1fb55bd8dccbeaaf1359e05496ad6715a536f511c7765216d4a3debe6e36e9128cbad613b8a48eb849973271ae80e3865efcc8eb7be6c9520ffd6a52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
